[2022-11-01T14:39:24.773] [INFO] default - Topic with id: 101 was Not Found. Try with other ID.
[2022-11-01T14:39:36.448] [ERROR] default - Failed to create Topic [Error [ValidationError]: "title" length must be less than or equal to 50 characters long] {
  _original: {
    title: 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc',
    description: 'Some text for description'
  },
  details: [
    {
      message: '"title" length must be less than or equal to 50 characters long',
      path: [Array],
      type: 'string.max',
      context: [Object]
    }
  ]
}
[2022-11-01T14:41:22.073] [ERROR] default - Failed to create Topiccccc [Error [ValidationError]: "title" length must be less than or equal to 50 characters long] {
  _original: {
    title: 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc',
    description: 'Some text for description'
  },
  details: [
    {
      message: '"title" length must be less than or equal to 50 characters long',
      path: [Array],
      type: 'string.max',
      context: [Object]
    }
  ]
}
[2022-11-01T14:42:14.378] [ERROR] default - Failed to create Topic
[2022-11-01T14:42:41.575] [ERROR] default - Failed to create Topic undefined
[2022-11-01T14:49:29.174] [ERROR] default - Failed to create Topic [Error [ValidationError]: "title" length must be less than or equal to 50 characters long] {
  _original: {
    title: 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc',
    description: 'Some text for description'
  },
  details: [
    {
      message: '"title" length must be less than or equal to 50 characters long',
      path: [Array],
      type: 'string.max',
      context: [Object]
    }
  ]
}
[2022-11-01T14:50:26.487] [ERROR] default - Failed to create Topic Error: insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 14:50:26', 'Some text for description', 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc', '2022-11-01 14:50:26') - Data too long for column 'title' at row 1
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'title' at row 1",
  sql: "insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 14:50:26', 'Some text for description', 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc', '2022-11-01 14:50:26')"
}
[2022-11-01T15:02:14.849] [ERROR] default - "title" length must be less than or equal to 50 characters long
[2022-11-01T15:03:25.820] [ERROR] default - "title" length must be less than or equal to 50 characters long
[2022-11-01T15:03:45.102] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T15:20:38.018] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T15:50:08.966] [ERROR] default - "title" length must be less than or equal to 50 characters long
[2022-11-01T15:50:09.188] [ERROR] default - Failed to create Topic
[2022-11-01T15:51:34.036] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T16:07:59.992] [INFO] default - Topic with id: a was Not Found. Try with other ID.
[2022-11-01T16:14:53.295] [ERROR] default - Failed to create Topic Error: insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 16:14:53', 'Some text for description', 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc', '2022-11-01 16:14:53') - Data too long for column 'title' at row 1
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'title' at row 1",
  sql: "insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 16:14:53', 'Some text for description', 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc', '2022-11-01 16:14:53')"
}
[2022-11-01T16:16:11.131] [ERROR] default - Failed to create Topic..... Error: insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 16:16:10', 'Some text for description', 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc', '2022-11-01 16:16:10') - Data too long for column 'title' at row 1
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'title' at row 1",
  sql: "insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 16:16:10', 'Some text for description', 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc', '2022-11-01 16:16:10')"
}
[2022-11-01T16:16:36.311] [ERROR] default - Failed to create Topic..... Data too long for column 'title' at row 1
[2022-11-01T16:16:54.564] [ERROR] default - Failed to create Topic:  Data too long for column 'title' at row 1
[2022-11-01T16:18:13.337] [ERROR] default - Failed to create Topic:  Data too long for column 'title' at row 1
[2022-11-01T16:18:31.131] [ERROR] default - Failed to create Topic:  Data too long for column 'description' at row 1
[2022-11-01T16:18:46.448] [ERROR] default - Failed to create Topic:  Data too long for column 'description' at row 1
[2022-11-01T16:19:01.766] [ERROR] default - Failed to create Topic:  Data too long for column 'title' at row 1
[2022-11-01T16:21:29.103] [ERROR] default - Failed to create Topic:  Data too long for column 'title' at row 1
[2022-11-01T16:22:08.044] [ERROR] default - Failed to create Topic:  Data too long for column 'title' at row 1
[2022-11-01T16:22:38.020] [ERROR] default - Failed to create Topic:  Error: insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 16:22:37', 'Some text for description', 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc', '2022-11-01 16:22:37') - Data too long for column 'title' at row 1
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'title' at row 1",
  sql: "insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 16:22:37', 'Some text for description', 'First Topicc First TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst TopiccFirst Topicc', '2022-11-01 16:22:37')"
}
[2022-11-01T16:31:13.935] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T16:31:56.637] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T16:32:30.372] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T16:45:35.316] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T16:49:54.452] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T16:51:29.362] [ERROR] default - Failed to create Topic:  Error: insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 16:51:29', 'Some text for description', 'First Topic', '2022-11-01 16:51:29') - Duplicate entry 'First Topic' for key 'topics_title_unique'
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry 'First Topic' for key 'topics_title_unique'",
  sql: "insert into `topics` (`created_at`, `description`, `title`, `updated_at`) values ('2022-11-01 16:51:29', 'Some text for description', 'First Topic', '2022-11-01 16:51:29')"
}
[2022-11-01T16:51:52.399] [ERROR] default - Failed to create Topic:  Duplicate entry 'First Topic' for key 'topics_title_unique'
[2022-11-01T16:52:14.665] [ERROR] default - Failed to create Topic:  Duplicate entry 'First Topic' for key 'topics_title_unique'
[2022-11-01T16:53:11.439] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T16:55:22.849] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T16:55:54.748] [ERROR] default - Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.delete (/app/app/Controllers/Http/TopicsController.ts:69:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T17:43:29.873] [INFO] default - Failed to get Topic Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.getTopic (/app/app/Controllers/Http/TopicsController.ts:22:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T17:43:46.611] [INFO] default - Failed to get Topic E_ROW_NOT_FOUND: Row not found
[2022-11-01T17:45:59.704] [INFO] default - Topic with id: 102 was Not Found. Try with other ID.
[2022-11-01T17:46:11.978] [ERROR] default - undefined
[2022-11-01T17:47:06.870] [ERROR] default - Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:44:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T20:01:03.354] [ERROR] default - Failed to create Topic:  undefined
[2022-11-01T20:01:17.516] [ERROR] default - Failed to create Topic:  ValidationException: E_VALIDATION_FAILURE: Validation Exception
    at ApiErrorReporter.toError (/app/node_modules/@adonisjs/validator/build/src/ErrorReporter/Api.js:49:16)
    at eval (eval at compile (/app/node_modules/@adonisjs/validator/build/src/Compiler/index.js:217:16), <anonymous>:51:31)
    at validate (/app/node_modules/@adonisjs/validator/build/src/Validator/index.js:114:72)
    at Request.validateRequest [as validate] (/app/node_modules/@adonisjs/validator/build/src/Bindings/Request.js:48:37)
    at TopicsController.create (/app/app/Controllers/Http/TopicsController.ts:39:37)
    at Injector.callAsync (/app/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  flashToSession: false,
  messages: { errors: [ [Object] ] }
}
[2022-11-01T20:01:39.843] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:02:30.007] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:03:05.565] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:03:21.472] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:03:50.334] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:04:02.055] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:04:23.497] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:53:06.208] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:53:18.093] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:53:38.710] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:54:02.380] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:54:37.000] [ERROR] default - Failed to create Topic:  ValidationException: E_VALIDATION_FAILURE: Validation Exception
    at ApiErrorReporter.toError (/app/node_modules/@adonisjs/validator/build/src/ErrorReporter/Api.js:49:16)
    at eval (eval at compile (/app/node_modules/@adonisjs/validator/build/src/Compiler/index.js:217:16), <anonymous>:51:31)
    at validate (/app/node_modules/@adonisjs/validator/build/src/Validator/index.js:114:72)
    at Request.validateRequest [as validate] (/app/node_modules/@adonisjs/validator/build/src/Bindings/Request.js:48:37)
    at TopicsController.create (/app/app/Controllers/Http/TopicsController.ts:33:37)
    at Injector.callAsync (/app/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  flashToSession: false,
  messages: { errors: [ [Object] ] }
}
[2022-11-01T20:57:23.406] [ERROR] default - Failed to create Topic:  ValidationException: E_VALIDATION_FAILURE: Validation Exception
    at ApiErrorReporter.toError (/app/node_modules/@adonisjs/validator/build/src/ErrorReporter/Api.js:49:16)
    at eval (eval at compile (/app/node_modules/@adonisjs/validator/build/src/Compiler/index.js:217:16), <anonymous>:51:31)
    at validate (/app/node_modules/@adonisjs/validator/build/src/Validator/index.js:114:72)
    at Request.validateRequest [as validate] (/app/node_modules/@adonisjs/validator/build/src/Bindings/Request.js:48:37)
    at TopicsController.create (/app/app/Controllers/Http/TopicsController.ts:33:37)
    at Injector.callAsync (/app/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  flashToSession: false,
  messages: { errors: [ [Object] ] }
}
[2022-11-01T20:57:38.843] [ERROR] default - Failed to create Topic:  ValidationException: E_VALIDATION_FAILURE: Validation Exception
    at ApiErrorReporter.toError (/app/node_modules/@adonisjs/validator/build/src/ErrorReporter/Api.js:49:16)
    at eval (eval at compile (/app/node_modules/@adonisjs/validator/build/src/Compiler/index.js:217:16), <anonymous>:51:31)
    at validate (/app/node_modules/@adonisjs/validator/build/src/Validator/index.js:114:72)
    at Request.validateRequest [as validate] (/app/node_modules/@adonisjs/validator/build/src/Bindings/Request.js:48:37)
    at TopicsController.create (/app/app/Controllers/Http/TopicsController.ts:33:37)
    at Injector.callAsync (/app/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  flashToSession: false,
  messages: { errors: [ [Object] ] }
}
[2022-11-01T20:57:57.353] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:58:17.360] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:58:38.222] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:58:58.789] [ERROR] default - Failed to create Topic:  E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T20:59:47.414] [ERROR] default - Failed to create Topic:  {
  errors: [
    {
      rule: 'maxLength',
      field: 'title',
      message: 'maxLength validation failed',
      args: [Object]
    }
  ]
}
[2022-11-01T21:15:35.962] [ERROR] default - E_ROW_NOT_FOUND: Row not found
[2022-11-01T21:15:56.371] [ERROR] default - E_ROW_NOT_FOUND: Row not found
[2022-11-01T21:16:11.885] [ERROR] default - Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:47:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T21:16:49.721] [ERROR] default - undefined
[2022-11-01T21:17:01.617] [ERROR] default - Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:47:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T21:26:01.994] [ERROR] default - ValidationException: E_VALIDATION_FAILURE: Validation Exception
    at ApiErrorReporter.toError (/app/node_modules/@adonisjs/validator/build/src/ErrorReporter/Api.js:49:16)
    at eval (eval at compile (/app/node_modules/@adonisjs/validator/build/src/Compiler/index.js:217:16), <anonymous>:51:31)
    at validate (/app/node_modules/@adonisjs/validator/build/src/Validator/index.js:114:72)
    at Request.validateRequest [as validate] (/app/node_modules/@adonisjs/validator/build/src/Bindings/Request.js:48:37)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:46:37)
    at Injector.callAsync (/app/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  flashToSession: false,
  messages: { errors: [ [Object] ] }
}
[2022-11-01T21:26:23.330] [ERROR] default - ValidationException: E_VALIDATION_FAILURE: Validation Exception
    at ApiErrorReporter.toError (/app/node_modules/@adonisjs/validator/build/src/ErrorReporter/Api.js:49:16)
    at eval (eval at compile (/app/node_modules/@adonisjs/validator/build/src/Compiler/index.js:217:16), <anonymous>:51:31)
    at validate (/app/node_modules/@adonisjs/validator/build/src/Validator/index.js:114:72)
    at Request.validateRequest [as validate] (/app/node_modules/@adonisjs/validator/build/src/Bindings/Request.js:48:37)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:46:37)
    at Injector.callAsync (/app/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  flashToSession: false,
  messages: { errors: [ [Object] ] }
}
[2022-11-01T21:26:43.709] [ERROR] default - ValidationException: E_VALIDATION_FAILURE: Validation Exception
    at ApiErrorReporter.toError (/app/node_modules/@adonisjs/validator/build/src/ErrorReporter/Api.js:49:16)
    at eval (eval at compile (/app/node_modules/@adonisjs/validator/build/src/Compiler/index.js:217:16), <anonymous>:51:31)
    at validate (/app/node_modules/@adonisjs/validator/build/src/Validator/index.js:114:72)
    at Request.validateRequest [as validate] (/app/node_modules/@adonisjs/validator/build/src/Bindings/Request.js:48:37)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:46:37)
    at Injector.callAsync (/app/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  flashToSession: false,
  messages: { errors: [ [Object] ] }
}
[2022-11-01T21:27:00.633] [ERROR] default - Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:47:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T21:27:17.942] [ERROR] default - Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:47:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T21:29:31.411] [ERROR] default - Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:47:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T21:32:30.785] [ERROR] default - Failed to get Topic: 101 E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T21:33:16.576] [ERROR] default - Failed to get Topic: 101 E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T21:33:30.667] [ERROR] default - Failed to get Topic: 101 E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T21:33:56.809] [ERROR] default - Failed to get Topic: 101 E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T21:34:29.141] [ERROR] default - E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T21:34:54.899] [ERROR] default - Failed to get Topic: 101 E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T21:35:30.555] [ERROR] default - Failed to get Topic: 101 E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T21:35:43.376] [ERROR] default - Failed to get Topic: 101 E_VALIDATION_FAILURE: Validation Exception
[2022-11-01T21:40:18.063] [ERROR] default - Exception: E_ROW_NOT_FOUND: Row not found
    at ModelQueryBuilder.firstOrFail (/app/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:426:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:47:21)
    at Object.PreCompiler.runRouteHandler [as fn] (/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)
    at Server.handleRequest (/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)
[2022-11-01T21:40:42.673] [ERROR] default - E_ROW_NOT_FOUND: Row not found
[2022-11-01T21:41:18.226] [ERROR] default - ValidationException: E_VALIDATION_FAILURE: Validation Exception
    at ApiErrorReporter.toError (/app/node_modules/@adonisjs/validator/build/src/ErrorReporter/Api.js:49:16)
    at eval (eval at compile (/app/node_modules/@adonisjs/validator/build/src/Compiler/index.js:217:16), <anonymous>:51:31)
    at validate (/app/node_modules/@adonisjs/validator/build/src/Validator/index.js:114:72)
    at Request.validateRequest [as validate] (/app/node_modules/@adonisjs/validator/build/src/Bindings/Request.js:48:37)
    at TopicsController.update (/app/app/Controllers/Http/TopicsController.ts:46:37)
    at Injector.callAsync (/app/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  flashToSession: false,
  messages: { errors: [ [Object] ] }
}
